#!/usr/bin/env python3
"""Generate the tiny C++ adapter that repairs the supported ROM in memory."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path


ROM_SHA1 = "e87e9338d7842db68a7a1e77bd5fc5b2bc8b2b72"
ROM_SIZE = 0x3E0000


def load_patch_module(path: Path):
    spec = importlib.util.spec_from_file_location("space_harrier_rompatch", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def byte_rows(blob: bytes, width: int = 12) -> str:
    return "\n".join(
        "        " + ", ".join(f"0x{value:02x}" for value in blob[pos : pos + width]) + ","
        for pos in range(0, len(blob), width)
    )


def render(module) -> str:
    words = module.ROMS[ROM_SHA1][1]
    extra = module.EXTRA_PATCHES[ROM_SHA1]

    payload = bytearray()
    descriptors = []
    for offset, _before, after, _description in extra:
        descriptors.append((offset, len(after), len(payload)))
        payload.extend(after)

    word_lines = "\n".join(
        f"        {{ 0x{offset:06x}, 0x{after:04x} }},"
        for offset, _before, after, _mnemonic, _source in words
    )
    descriptor_lines = "\n".join(
        f"        {{ 0x{offset:06x}, {size}, {data_offset} }},"
        for offset, size, data_offset in descriptors
    )

    return f'''// Generated by scripts/generate_rom_patch_header.py. Do not edit.
// license:GPL-2.0-or-later
#pragma once

#include "util/hashing.h"

#include <algorithm>
#include <cstdint>
#include <string>

namespace sh1_mdp_rom {{

struct word_patch
{{
    std::uint32_t offset;
    std::uint16_t value;
}};

struct byte_patch
{{
    std::uint32_t offset;
    std::uint16_t size;
    std::uint16_t data_offset;
}};

inline bool apply(std::uint8_t *rom, std::uint32_t size)
{{
    constexpr std::uint32_t expected_size = 0x{ROM_SIZE:x};
    if (size != expected_size)
        return false;

    const std::string sha1 = util::sha1_creator::simple(rom, size).as_string();
    if (sha1 != "{ROM_SHA1}")
        return false;

    static constexpr word_patch words[] = {{
{word_lines}
    }};
    for (const word_patch &patch : words)
    {{
        rom[patch.offset] = patch.value >> 8;
        rom[patch.offset + 1] = patch.value & 0xff;
    }}

    static constexpr byte_patch blocks[] = {{
{descriptor_lines}
    }};
    static constexpr std::uint8_t data[] = {{
{byte_rows(payload)}
    }};
    for (const byte_patch &patch : blocks)
        std::copy_n(data + patch.data_offset, patch.size, rom + patch.offset);

    return true;
}}

}} // namespace sh1_mdp_rom
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("patch_module", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(load_patch_module(args.patch_module)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
