#!/usr/bin/env python3
"""Generate the tiny C++ adapter that repairs the supported ROM in memory."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path


ROM_SIZES = {
    "e87e9338d7842db68a7a1e77bd5fc5b2bc8b2b72": 0x3E0000,
    "80f576af01d6413c0b92073e2f947b0431f12a74": 0x380000,
}


def load_patch_module(path: Path):
    spec = importlib.util.spec_from_file_location("space_harrier_rompatch", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def byte_rows(blob: bytes, width: int = 12) -> str:
    return "\n".join(
        "        " + ", ".join(f"0x{value:02x}" for value in blob[pos : pos + width]) + ","
        for pos in range(0, len(blob), width)
    )


def render(module) -> str:
    cases = []
    for index, (sha1, (name, words)) in enumerate(module.ROMS.items()):
        if sha1 not in ROM_SIZES:
            raise RuntimeError(f"missing ROM size for {name} ({sha1})")
        extra = module.EXTRA_PATCHES.get(sha1, ())
        payload = bytearray()
        descriptors = []
        for offset, _before, after, _description in extra:
            descriptors.append((offset, len(after), len(payload)))
            payload.extend(after)

        word_lines = "\n".join(
            f"            {{ 0x{offset:06x}, 0x{after:04x} }},"
            for offset, _before, after, _mnemonic, _source in words
        )
        descriptor_lines = "\n".join(
            f"            {{ 0x{offset:06x}, {size}, {data_offset} }},"
            for offset, size, data_offset in descriptors
        ) or "            { 0x000000, 0, 0 },"
        data_lines = byte_rows(payload) if payload else "        0x00,"
        text_compat = "true" if sha1 == "80f576af01d6413c0b92073e2f947b0431f12a74" else "false"
        cases.append(f'''    if (size == 0x{ROM_SIZES[sha1]:x} && sha1 == "{sha1}")
    {{
        static constexpr word_patch words_{index}[] = {{
{word_lines}
        }};
        for (const word_patch &patch : words_{index})
        {{
            rom[patch.offset] = patch.value >> 8;
            rom[patch.offset + 1] = patch.value & 0xff;
        }}

        static constexpr byte_patch blocks_{index}[] = {{
{descriptor_lines}
        }};
        static constexpr std::uint8_t data_{index}[] = {{
{data_lines}
        }};
        for (const byte_patch &patch : blocks_{index})
            std::copy_n(data_{index} + patch.data_offset, patch.size, rom + patch.offset);
        if (sh2_text_compat)
            *sh2_text_compat = {text_compat};
        return true;
    }}''')

    return f'''// Generated by scripts/generate_rom_patch_header.py. Do not edit.
// license:GPL-2.0-or-later
#pragma once

#include "util/hashing.h"

#include <algorithm>
#include <cstdint>
#include <string>

namespace sh1_mdp_rom {{

struct word_patch
{{
    std::uint32_t offset;
    std::uint16_t value;
}};

struct byte_patch
{{
    std::uint32_t offset;
    std::uint16_t size;
    std::uint16_t data_offset;
}};

// The legacy SH2 font-bank workaround is a game compatibility setting, not a
// VDP rule. Never enable it for SH1 or an unrecognised cartridge.
inline bool apply(std::uint8_t *rom, std::uint32_t size, bool *sh2_text_compat = nullptr)
{{
    if (sh2_text_compat)
        *sh2_text_compat = false;
    const std::string sha1 = util::sha1_creator::simple(rom, size).as_string();
{chr(10).join(cases)}
    return false;
}}

}} // namespace sh1_mdp_rom
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("patch_module", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(load_patch_module(args.patch_module)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
